<?php

namespace Database\Seeders;

use App\Models\Article;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin_wilayah')->first();
        if (!$admin) {
            $admin = User::first();
        }

        $articlesData = [
            // -- Published (12 articles) --
            [
                'title'            => 'Protein hewani harian untuk pertumbuhan optimal anak',
                'category'         => 'Gizi Anak',
                'summary'          => 'Pentingnya protein hewani setiap hari untuk mendukung tumbuh kembang anak dan pencegahan stunting.',
                'content'          => "# Protein Hewani\n\nProtein hewani dibutuhkan untuk pembentukan jaringan tubuh dan mendukung pertumbuhan anak.\n\n- Telur\n- Ikan\n- Daging ayam\n- Hati\n- Susu",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => true,
                'read_time'        => 6,
                'published_date'   => now()->subDays(5),
            ],
            [
                'title'            => 'ASI Eksklusif: Manfaat dan Cara Pemberian yang Benar',
                'category'         => 'ASI Eksklusif',
                'summary'          => 'Panduan pemberian ASI eksklusif selama 6 bulan pertama kehidupan anak.',
                'content'          => "# ASI Eksklusif\n\nASI eksklusif selama 6 bulan pertama adalah investasi terbaik untuk kesehatan anak jangka panjang.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => true,
                'read_time'        => 5,
                'published_date'   => now()->subDays(2),
            ],
            [
                'title'            => 'Pentingnya Memantau Tinggi Badan Anak Secara Berkala',
                'category'         => 'Gizi Anak',
                'summary'          => 'Pemantauan tinggi badan secara berkala membantu mendeteksi risiko stunting sejak dini.',
                'content'          => "# Pemantauan Tinggi Badan\n\nTinggi badan yang tidak sesuai usia adalah tanda pertama risiko stunting yang perlu ditangani segera.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => now()->subDays(7),
            ],
            [
                'title'            => 'Menu Makanan Kaya Zat Besi untuk Mencegah Anemia',
                'category'         => 'Gizi Anak',
                'summary'          => 'Panduan lengkap menu harian kaya zat besi yang mudah disiapkan untuk balita.',
                'content'          => "# Zat Besi untuk Anak\n\nKekurangan zat besi dapat memperlambat perkembangan otak dan fisik anak.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->subDays(9),
            ],
            [
                'title'            => 'Peran Imunisasi Lengkap dalam Mencegah Stunting pada Balita',
                'category'         => 'FAQ',
                'summary'          => 'Imunisasi rutin melindungi anak dari penyakit infeksi yang dapat memperburuk kondisi gizi.',
                'content'          => "# Imunisasi dan Stunting\n\nInfeksi berulang adalah salah satu penyebab utama stunting. Imunisasi adalah pertahanan pertama.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => false,
                'read_time'        => 6,
                'published_date'   => now()->subDays(12),
            ],
            [
                'title'            => 'Kebutuhan Vitamin D dan Kalsium untuk Pertumbuhan Tulang Anak',
                'category'         => 'Gizi Anak',
                'summary'          => 'Vitamin D dan kalsium bekerja bersama untuk membangun tulang yang kuat pada anak.',
                'content'          => "# Vitamin D dan Kalsium\n\nPaparan sinar matahari pagi dan konsumsi susu setiap hari adalah cara terbaik memenuhi kebutuhan ini.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->subDays(14),
            ],
            [
                'title'            => 'Cara Menyimpan ASI Perah agar Nutrisinya Tetap Terjaga',
                'category'         => 'ASI Eksklusif',
                'summary'          => 'Teknik penyimpanan ASI yang tepat untuk menjaga kandungan gizi dan keamanannya.',
                'content'          => "# Penyimpanan ASI Perah\n\nASI perah dapat disimpan di kulkas hingga 4 hari dan di freezer hingga 6 bulan.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => now()->subDays(16),
            ],
            [
                'title'            => 'Mitos dan Fakta seputar Tumbuh Kembang Anak',
                'category'         => 'FAQ',
                'summary'          => 'Meluruskan berbagai mitos yang beredar di masyarakat tentang pertumbuhan balita.',
                'content'          => "# Mitos dan Fakta Tumbuh Kembang\n\nBanyak mitos yang justru dapat membahayakan tumbuh kembang anak jika dipercaya.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 7,
                'published_date'   => now()->subDays(18),
            ],
            [
                'title'            => 'Pentingnya Posyandu dalam Memantau Kesehatan Ibu dan Anak',
                'category'         => 'FAQ',
                'summary'          => 'Posyandu adalah garda terdepan pemantauan gizi dan kesehatan anak di Indonesia.',
                'content'          => "# Peran Posyandu\n\nKunjungan rutin ke posyandu setiap bulan membantu mendeteksi masalah gizi sejak dini.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => true,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->subDays(20),
            ],
            [
                'title'            => 'Manfaat Sayuran Hijau dan Buah Berwarna Kuning untuk Balita',
                'category'         => 'Gizi Anak',
                'summary'          => 'Panduan praktis mengenalkan aneka sayuran dan buah yang kaya vitamin A untuk balita.',
                'content'          => "# Sayuran dan Buah untuk Balita\n\nWartel, labu, dan bayam adalah sumber vitamin A terbaik untuk mendukung imunitas anak.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => now()->subDays(22),
            ],
            [
                'title'            => 'Berapa Berat Badan Ideal untuk Balita Usia 2 Tahun?',
                'category'         => 'FAQ',
                'summary'          => 'Panduan berat badan normal balita usia 2 tahun berdasarkan standar WHO.',
                'content'          => "# Berat Badan Ideal Balita\n\nMenurut WHO, berat badan normal anak usia 2 tahun adalah 12-14 kg untuk laki-laki dan 11-14 kg untuk perempuan.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 3,
                'published_date'   => now()->subDays(25),
            ],
            [
                'title'            => 'Kenali Pola Tidur yang Baik untuk Dukung Hormon Pertumbuhan',
                'category'         => 'Gizi Anak',
                'summary'          => 'Tidur yang cukup dan berkualitas adalah kunci produksi hormon pertumbuhan optimal pada anak.',
                'content'          => "# Pola Tidur dan Pertumbuhan\n\nHormon pertumbuhan diproduksi terutama saat tidur nyenyak. Anak usia 1-3 tahun membutuhkan 12-14 jam tidur per hari.",
                'status'           => 'published',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->subDays(28),
            ],

            // -- Draft (8 articles) --
            [
                'title'            => 'Panduan MPASI bergizi untuk usia 6?24 bulan',
                'category'         => 'MPASI',
                'summary'          => 'Contoh menu MPASI seimbang dengan sumber protein hewani, nabati, dan sayur.',
                'content'          => "# Panduan MPASI\n\nMakanan pendamping ASI perlu diberikan dengan komposisi gizi yang seimbang.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 8,
                'published_date'   => null,
            ],
            [
                'title'            => 'Bagaimana Mengatasi Anak yang Pilih-Pilih Makanan (Picky Eater)',
                'category'         => 'MPASI',
                'summary'          => 'Strategi efektif untuk mengatasi anak yang menolak makan beragam jenis makanan.',
                'content'          => "# Picky Eater\n\nAnak picky eater berisiko kekurangan gizi. Perkenalkan makanan baru secara bertahap dengan cara yang menyenangkan.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 6,
                'published_date'   => null,
            ],
            [
                'title'            => 'Dampak Sanitasi Lingkungan yang Buruk terhadap Risiko Stunting',
                'category'         => 'FAQ',
                'summary'          => 'Sanitasi buruk adalah faktor lingkungan terbesar yang berkontribusi pada stunting.',
                'content'          => "# Sanitasi dan Stunting\n\nAnak yang tinggal di lingkungan tanpa akses air bersih dan sanitasi layak 3x lebih berisiko mengalami stunting.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 7,
                'published_date'   => null,
            ],
            [
                'title'            => 'Mengenal Tanda-Tanda Awal Kurang Gizi pada Bayi',
                'category'         => 'Gizi Anak',
                'summary'          => 'Deteksi dini tanda-tanda kekurangan gizi agar dapat segera ditangani.',
                'content'          => "# Tanda Kurang Gizi\n\nBerat badan turun, kulit kusam, rambut rontok, dan lesu adalah tanda-tanda awal kurang gizi yang perlu diwaspadai.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => null,
            ],
            [
                'title'            => 'Tips Menyiapkan MPASI Sehat Saat Bepergian',
                'category'         => 'MPASI',
                'summary'          => 'Cara praktis mempersiapkan makanan bergizi untuk bayi saat bepergian jauh.',
                'content'          => "# MPASI saat Bepergian\n\nSiapkan MPASI instan higienis atau bawa bahan segar dalam cooler bag untuk perjalanan.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => null,
            ],
            [
                'title'            => 'Mengatasi Kolik pada Bayi Baru Lahir: Panduan untuk Orang Tua',
                'category'         => 'ASI Eksklusif',
                'summary'          => 'Panduan praktis untuk orang tua dalam menghadapi bayi yang mengalami kolik.',
                'content'          => "# Kolik pada Bayi\n\nKolik biasanya terjadi pada bayi usia 2-4 minggu dan memuncak pada usia 6 minggu.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 6,
                'published_date'   => null,
            ],
            [
                'title'            => 'Cara Menghitung Tinggi Potensi Genetik Anak Sejak Dini',
                'category'         => 'FAQ',
                'summary'          => 'Formula sederhana untuk memperkirakan tinggi badan dewasa anak berdasarkan tinggi orang tua.',
                'content'          => "# Potensi Genetik Tinggi Badan\n\nTinggi potensi genetik = (tinggi ayah + tinggi ibu ? 13) / 2. Formula ini hanya estimasi.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => null,
            ],
            [
                'title'            => 'Panduan Memilih Susu Formula Pendamping Jika ASI Terhambat',
                'category'         => 'ASI Eksklusif',
                'summary'          => 'Kriteria memilih susu formula yang tepat sesuai usia dan kondisi kesehatan anak.',
                'content'          => "# Susu Formula Pendamping\n\nPilih susu formula yang sesuai usia dengan kandungan DHA, ARA, dan prebiotik yang cukup.",
                'status'           => 'draft',
                'is_published'     => false,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => null,
            ],

            // -- Scheduled (5 articles) --
            [
                'title'            => 'Pentingnya Sarapan Pagi Bagi Konsentrasi Belajar Anak',
                'category'         => 'Gizi Anak',
                'summary'          => 'Sarapan bergizi meningkatkan konsentrasi dan daya ingat anak di sekolah.',
                'content'          => "# Sarapan dan Konsentrasi\n\nAnak yang sarapan terbukti memiliki nilai akademis lebih baik dibanding yang tidak sarapan.",
                'status'           => 'scheduled',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => now()->addDays(3),
            ],
            [
                'title'            => 'Stimulasi Motorik Kasar dan Halus pada Anak Usia 1-3 Tahun',
                'category'         => 'FAQ',
                'summary'          => 'Panduan stimulasi tumbuh kembang motorik anak usia toddler untuk orang tua.',
                'content'          => "# Stimulasi Motorik Anak\n\nAktivitas bermain yang tepat dapat merangsang perkembangan motorik kasar dan halus secara bersamaan.",
                'status'           => 'scheduled',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 6,
                'published_date'   => now()->addDays(5),
            ],
            [
                'title'            => 'Mengapa Garam Beryodium Sangat Penting untuk Ibu Hamil dan Anak',
                'category'         => 'Gizi Anak',
                'summary'          => 'Defisiensi yodium pada ibu hamil dapat menyebabkan gangguan perkembangan otak janin.',
                'content'          => "# Yodium untuk Ibu dan Anak\n\nGunakan selalu garam beryodium dalam masakan sehari-hari untuk mencegah gondok dan kretenisme.",
                'status'           => 'scheduled',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->addDays(7),
            ],
            [
                'title'            => 'Kapan Waktu yang Tepat Mengenalkan Makanan Padat pada Bayi?',
                'category'         => 'MPASI',
                'summary'          => 'WHO merekomendasikan MPASI dimulai tepat saat bayi berusia 6 bulan.',
                'content'          => "# Waktu Tepat MPASI\n\nPemberian MPASI terlalu dini atau terlambat sama-sama berisiko terhadap tumbuh kembang anak.",
                'status'           => 'scheduled',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 5,
                'published_date'   => now()->addDays(10),
            ],
            [
                'title'            => 'Hubungan Antara Kesehatan Gigi Anak dengan Nafsu Makan',
                'category'         => 'FAQ',
                'summary'          => 'Gigi berlubang atau gusi bermasalah bisa menjadi penyebab tersembunyi anak susah makan.',
                'content'          => "# Kesehatan Gigi dan Nafsu Makan\n\nNyeri akibat karies gigi membuat anak menghindari makanan keras, yang dapat berujung pada kekurangan gizi.",
                'status'           => 'scheduled',
                'is_published'     => true,
                'show_on_homepage' => false,
                'is_featured'      => false,
                'read_time'        => 4,
                'published_date'   => now()->addDays(14),
            ],
        ];

        foreach ($articlesData as $a) {
            Article::create(array_merge($a, [
                'author_name' => 'Tim Edukasi SiCegah',
                'slug'        => Str::slug($a['title']),
                'user_id'     => $admin?->id,
            ]));
        }
    }
}